services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./app:/workspace/app:ro
      - ./bs-config.cjs:/workspace/bs-config.cjs:ro
