'use strict';
const DX7Profile=(()=>{
const spec=(key,title)=>[key,title,...DX7.ranges[key]];
const globalSpecs=[spec('ALG','Algorithm'),spec('FBL','Feedback'),spec('SPD','LFO speed'),spec('DLY','LFO delay'),['LFW','LFO waveform',['Triangle','Saw down','Saw up','Square','Sine','Sample and hold']],spec('PMD','Pitch modulation depth'),spec('AMD','Amplitude modulation depth'),['SYNC','LFO key sync',['OFF','ON']],spec('PMS','Pitch modulation sensitivity'),['OKS','Oscillator key sync',['OFF','ON']],spec('TRPS','Transpose'),spec('AMS','Operator amplitude modulation sensitivity'),spec('KVS','Operator velocity sensitivity'),spec('RATE','Operator keyboard rate scaling')];
const opSpecs=[['FIX','Oscillator frequency mode',['RATIO','FIXED']],spec('CRS','Frequency coarse'),spec('FINE','Frequency fine'),spec('DET','Detune'),...['R1','L1','R2','L2','R3','L3','R4','L4'].map(k=>spec(k,'Envelope '+(k[0]==='R'?'rate ':'level ')+k[1])),spec('BP','Keyboard scaling breakpoint'),spec('LD','Left scaling depth'),spec('RD','Right scaling depth'),['LC','Left scaling curve',['−LIN','−EXP','+EXP','+LIN']],['RC','Right scaling curve',['−LIN','−EXP','+EXP','+LIN']],spec('OUT','Output level')];
const pitchSpecs=['PR1','PL1','PR2','PL2','PR3','PL3','PR4','PL4'].map(k=>spec(k,'Pitch envelope '+(k[1]==='R'?'rate ':'level ')+k[2]));
const dialogs={...YS200Profile.dialogs,about:['DX7 / 6 OP EDITOR','<p>Original Yamaha DX7 voice editor. Six sine operators, 32 algorithms and native four-rate/four-level envelopes.</p><p>Local editing and DX7 SysEx files are supported. Audio synthesis and live MIDI transport are not connected.</p>'],midi:['DX7 MIDI','<p>Live MIDI transport is not connected. Use the file menu to import a DX7 single voice or 32-voice bank, or export the edited voice as .syx.</p><p>The original DX7 transmits on channel 1 and receives on channels 1–16. Voice edits use Yamaha parameter-change SysEx, not ordinary CC messages.</p>'],help:['DX7 HELP','<p>6 OP selects the original DX7; 4 OP selects YS200. Each engine keeps its own edits and undo history during this session.</p><p>Select C / M or an algorithm operator to edit it. PITCH opens the shared pitch envelope controls; VOICE returns to operator controls.</p><p>Amplitude EG: L4 is the starting and release level. R1–R3 move through L1–L3, with L3 held until key release; R4 returns to L4. Levels can rise or fall. Pitch level 50 is neutral.</p><p>Graphs show relative stage shapes, not hardware timing or calibrated gain/pitch. Operator ON/OFF is temporary edit state and is not stored in voice SysEx. JSON snapshots retain it.</p><p>The diamond opens voice and bank import/export. No automatic conversion between engines or audio playback is provided.</p>'],file:['DX7 VOICE FILES','<p>Import a single voice or 32-voice bank. Export the current voice as Yamaha SysEx or a JSON snapshot.</p><div class="dialog-actions"><button type="button" id="save-json">SAVE JSON</button><button type="button" id="save-syx">SAVE .SYX</button></div><p><label>SYSEX CHANNEL <select id="syx-channel"></select></label></p><p><label>OPEN .SYX <input type="file" id="load-syx" accept=".syx"></label></p><div id="bank-voices"></div><p id="file-result" role="status"></p>']};
function lfoWave(w){const path=['M3 16L16 5L42 27L55 16','M3 5L29 27V5L55 27','M3 27L29 5V27L55 5','M3 27V5H16V27H29V5H42V27H55V5','M3 16C12 0 20 0 29 16S46 32 55 16','M3 24H10V5H20V17H30V9H40V25H55'][w];return `<svg class="lfo-wave" viewBox="0 0 58 32" aria-hidden="true"><path d="${path}"/></svg>`;}
return {...DX7,id:'dx7',label:'Yamaha DX7',shortName:'DX7',status:'ready',operatorCount:6,polyphony:16,algorithmCount:32,envelopeModel:'four-rates-four-levels',envelopeDragMin:(_,min)=>min,nameLength:10,diagramWidth:196,globalSpecs,opSpecs,pitchSpecs,dialogs,lfoWave,waveNames:['Sine'],operatorSample:(_,p)=>Math.sin(2*Math.PI*p),scope:k=>DX7.operatorKeys.includes(k)||k==='wave'||k==='on'?'operator':'global',numberedLabel:k=>['AMS','KVS','RATE'].includes(k),formatValue:(k,v)=>k==='BP'?['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'][(v+9)%12]+(Math.floor((v+9)/12)-1):String(v),operatorSummary:op=>`${DX7.frequencyLabel(op)} DET:${op.DET>=0?'+':''}${op.DET}\nR:${op.R1} ${op.R2} ${op.R3} ${op.R4}\nL:${op.L1} ${op.L2} ${op.L3} ${op.L4} OUT:${op.OUT}`,seed:v=>v.operators.forEach(op=>{for(let n=1;n<=4;n++){op['R'+n]=Math.floor(Math.random()*100);op['L'+n]=n===4?0:Math.floor(Math.random()*100);}}),effects:null,midi:{voiceCodec:DX7Codec,transport:null},envelopeTitle:'Schematic DX7 envelope: L4 → L1 → L2 → L3, hold until key-off, then L4. Relative times and level indices; not calibrated hardware timing or gain.',captions:{global:[['',1,3],['LOW FREQUENCY OSCILLATOR',3,9],['VOICE',9,12],['OP SENSITIVITY',12,15]],operator:[['OSCILLATOR',1,5],['ENVELOPE GENERATOR',5,13],['KEYBOARD LEVEL SCALING',13,18],['OUT',18,19]]}};
})();
